# Mengatur gamerule server agar output command tidak muncul di log/cmd.
function apply_server_settings(p: player):
    set gamerule send_command_feedback of world of {_p} to false
    set gamerule log_admin_commands of world of {_p} to false
    set gamerule command_block_output of world of {_p} to false

on join:
    wait 1 tick
    apply_server_settings(player)

on respawn:
    wait 1 tick
    apply_server_settings(player)
