on player move:
    set {_x} to floor(x-coordinate of player)
    set {_y} to floor(y-coordinate of player)
    set {_z} to floor(z-coordinate of player)
    set {_pos} to "%world of player%::%{_x}%::%{_y}%::%{_z}%"
    if {bedrock.lastpos::%uuid of player%} is {_pos}:
        stop
    set {bedrock.lastpos::%uuid of player%} to {_pos}

    execute console command "execute at %player% run fill ~-7 -60 ~-7 ~7 -60 ~7 minecraft:bedrock replace"
