
options:
    clear-drops-interval: 1 seconds

function count_dropped_items() :: number:
    set {_count} to 0
    loop all entities:
        if loop-entity is a dropped item:
            if is_allowed_item(item of loop-entity) is false:
                add 1 to {_count}
    return {_count}

function clear_dropped_items() :: number:
    set {_removed} to 0
    loop all entities:
        if loop-entity is a dropped item:
            if is_allowed_item(item of loop-entity) is false:
                kill loop-entity
                add 1 to {_removed}
    return {_removed}

every {@clear-drops-interval}:
    clear_dropped_items()

command /cleardrops:
    trigger:
        clear_dropped_items()
