
on left click:
    set {_toolName} to "%type of player's tool%"
    if {_toolName} does not contain "sword":
        stop

    if {sword.reach.cooldown::%uuid of player%} is set:
        stop
    set {sword.reach.cooldown::%uuid of player%} to true

    set {_target} to target entity of player
    if {_target} is not set:
        delete {sword.reach.cooldown::%uuid of player%}
        stop

    if {_target} is dead:
        delete {sword.reach.cooldown::%uuid of player%}
        stop

    set {_dist} to distance between player and {_target}

    if {_dist} <= 3:
        delete {sword.reach.cooldown::%uuid of player%}
        stop

    if {_dist} > 11:
        delete {sword.reach.cooldown::%uuid of player%}
        stop

    set {_reachDamage} to 4
    set {_strengthLevel} to potion level of strength of player
    if {_strengthLevel} is set:
        if {_strengthLevel} > 0:
            add ({_strengthLevel} * 3) to {_reachDamage}

    damage {_target} by {_reachDamage}
    play sound "entity.player.attack.strong" with volume 1 and pitch 1 to player

    wait 2 ticks
    delete {sword.reach.cooldown::%uuid of player%}

on quit:
    delete {sword.reach.cooldown::%uuid of player%}
