# Teleport pemenang ke Y tertinggi di X/Z lokasi saat menang.

every 1 tick:
    if {win.last.id} is set:
        if {win.teleport.last.id} is not {win.last.id}:
            set {win.teleport.last.id} to {win.last.id}
            set {_winnerUuid} to {win.last.uuid}
            loop all players:
                if uuid of loop-player is {_winnerUuid}:
                    set {_tpLoc} to location of loop-player
                    set {_topBlock} to highest block at {_tpLoc}
                    set y-coordinate of {_tpLoc} to y-coordinate of {_topBlock}
                    add 1 to y-coordinate of {_tpLoc}
                    teleport loop-player to {_tpLoc}
                    stop
