



language: english

check for new version: true

update check interval: 12 hours

release channel: stable

enable effect commands: false
effect command token: !

allow ops to use effect commands: false

log effect commands: false


load default aliases: true


player variable fix: true

use player UUIDs in variable names: true


date format: default


verbosity: normal


plugin priority: high

listen to cancelled events by default: false

number accuracy: 2


maximum target block distance: 100


case sensitive: false

case-insensitive variables: true

case-insensitive commands: false

disable variable will not be saved warnings: false

disable variable missing and/or warnings: false

disable starting a variable's name with an expression warnings: false

disable single colon in variable name warnings: false

disable unreachable code warnings: false

soft api exceptions: false

enable timings: false

parse links in chat messages: disabled

color codes reset formatting: true

keep command last usage dates: false

script loader thread size: 0

use type properties: true

disable hooks:
	vault: false
	regions:
		grief prevention: false
		precious stones: false
		residence: false
		worldguard: false

player name regex pattern: [a-zA-Z0-9_]{1,16}

long parse time warning threshold: 0 seconds

variable changes until save: 1000


runtime errors:
	frame duration: 1 second

	total errors per frame: 8

	errors from one line per frame: 2

	error spam timeout limit: 4

	error timeout length: 10


	total warnings per frame: 8
	warnings from one line per frame: 2
	warning spam timeout limit: 4
	warning timeout length: 10



databases:

	database 1:

		type: disabled

		pattern: .*

		monitor changes: false
		monitor interval: 20 seconds

		host: localhost
		port: 3306
		user: root
		password: pass
		database: skript
		table: variables21
		file: ./plugins/Skript/variables.db


		backup interval: 2 hours

		backups to keep: -1


	MySQL example:

		type: disabled

		pattern: synced_.*

		host: localhost
		port: 3306
		user: root
		password: pass
		database: skript
		table: variables21

		monitor changes: true
		monitor interval: 20 seconds

	SQLite example:

		type: disabled

		pattern: db_.*

		file: ./plugins/Skript/variables.db

		backup interval: 0
		monitor changes: false
		monitor interval: 20 seconds

		backups to keep: -1

	default:

		type: CSV

		pattern: .*

		file: ./plugins/Skript/variables.csv

		backup interval: 2 hours

		backups to keep: -1






version: 2.14.3
